### ISSUE TITLE
[ Question ] Soundbort keeps leaving channel

### ISSUE THREAD

**Issue by timep3** [Soundbort/Soundbort#52]
Use the /join command and less than a minute later soundbort leaves the channel. Use a sound from /list and soundbort will join, play the sound, then leave less than a minute later. Didn't do this at first not sure what I did

**Comment by LonelessCodes** [comment]
Sorry for the late update. It seems like this is a problem with the underlying library. Gonna push an update as soon as i can.

**Comment by LonelessCodes** [comment]
The problem has been fixed
