### ISSUE TITLE
[ Bug ] ❌ File upload fails at ffprobe integrity check

### ISSUE THREAD

**Issue by Jkryv3nchuk** [Soundbort/Soundbort#8]
When trying to upload a file, I receive a `❌ Checking file integrity failed. Try another.` error message.

*Details*

- File name is `hello-there.mp3`
- Length is around 1 second
- File size is 19.0 KB

Seems like a cool bot so far and I'd love to use it on my server; Thanks for your time!

**Comment by LonelessCodes** [comment]
Oh I might know the problem. Investigating further.

**Comment by LonelessCodes** [comment]
Yes, currently every file upload failes. Shit! That's what I get from not properly testing

**Comment by LonelessCodes** [comment]
Problem with arm ffprobe-static `spawn /app/node_modules/ffprobe-static/bin/linux/arm/ffprobe ENOENT`

Fixed in 0db8f650300a41331e892faaa3bb7b6fb695840f
